name: matrix-appservice-irc
base: core18
version: git
summary: Node.js Matrix bridge for IRC
description: |
  A bridge between Matrix and IRC. Currently the bridge is in Beta.

grade: stable
confinement: strict

apps:
  matrix-appservice-irc:
    command: 'bin/node $SNAP/app.js -c $SNAP_COMMON/config.yaml -f $SNAP_COMMON/registration.yaml -p 9999'
    plugs: [network-bind, network]
    daemon: simple

parts:
  nodejs-lts:
    plugin: nil
    override-build: |
      NODE_VERSION=12.16.1
      case $SNAPCRAFT_ARCH_TRIPLET in
      x86_64-*)
        NODE_ARCH="x64"
        ;;
      aarch64-*)
        NODE_ARCH="arm64"
        ;;
      arm-linux-gnueabihf)
        NODE_ARCH="armv7l"
        ;;
      powerpc64le-*)
        NODE_ARCH="ppc64le"
        ;;
      s390x-*)
        NODE_ARCH="s390x"
        ;;
      esac
      echo "Fetching node $NODE_VERSION for $NODE_ARCH"
      wget "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-$NODE_ARCH.tar.xz" -O /tmp/nodejs.tar.xz
      tar Jxf /tmp/nodejs.tar.xz -C $SNAPCRAFT_PART_INSTALL/ --strip 1
      rm $SNAPCRAFT_PART_INSTALL/README.md
      rm $SNAPCRAFT_PART_INSTALL/CHANGELOG.md
      rm $SNAPCRAFT_PART_INSTALL/LICENSE
      snapcraftctl build
  matrix-appservice-irc:
    source: .
    plugin: dump
    build-packages:
      - make
      - gcc
      - g++
      - binutils
      - python
      - git
      - libicu-dev
    stage-packages:
      - sipcalc
      - iproute2
      - openssl
      - libicu60
      - libatm1
    after: [nodejs-lts]
