name: E2E tests

on:
  push:
    branches: ["develop", "release-*"]
  pull_request:
  workflow_dispatch:

jobs:
  build-synapse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout synapse
        uses: actions/checkout@v3
        with:
          repository: 'matrix-org/synapse'
          ref: 'master'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build matrixdotorg/synapse
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile
          tags: matrixdotorg/synapse:latest
      - name: Build matrixdotorg/synapse-workers
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/Dockerfile-workers
          tags: matrixdotorg/synapse-workers:latest
      - name: Build complement-synapse
        uses: docker/build-push-action@v3
        with:
          context: docker/complement
          file: docker/complement/Dockerfile
          build-args: SYNAPSE_VERSION=latest
          tags: complement-synapse:latest
          outputs: type=docker,dest=/tmp/img-synapse.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: img-synapse
          path: /tmp/img-synapse.tar

  inspircd-test:
    runs-on: ubuntu-latest
    needs:
      - build-synapse
    services:
      ircd:
        image: inspircd/inspircd-docker
        env:
          # Don't check domain against blacklists
          INSP_ENABLE_DNSBL: no
        ports:
          - 6667:6667
    steps:
      - name: "Set Go Version"
        run: |
          echo "$GOROOT_1_17_X64/bin" >> $GITHUB_PATH
          echo "~/go/bin" >> $GITHUB_PATH
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm ci
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Download synapse
        uses: actions/download-artifact@v3
        with:
          name: img-synapse
          path: /tmp
      - name: Load images
        run: |
          docker load --input /tmp/img-synapse.tar
      - name: Checkout matrix-org/complement
        uses: actions/checkout@v3
        with:
          repository: 'matrix-org/complement'
          ref: 'master'
          path: complement
      - name: "Install Complement Dependencies"
        # We don't need to install Go because it is included on the Ubuntu 20.04 image:
        # See https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md specifically GOROOT_1_17_X64
        run: |
          sudo apt-get update && sudo apt-get install -y libolm3 libolm-dev
      - name: "Build homerunner"
        run: |
          go build ./complement/cmd/homerunner
      - name: "Run Homerunner tests"
        run: |
          ./complement/homerunner &
          bash -ic 'npm run-script test:e2e'
